## https://github.com/erlef/docker-elixir/blob/359c4c4879581c2aa3b7722b910a1a99726e6771/1.14/Dockerfile
## Modified on 04/16/2023
FROM erlang:25

# elixir expects utf8.
ENV ELIXIR_VERSION="v1.14.4" \
	LANG=C.UTF-8

RUN set -xe \
	&& ELIXIR_DOWNLOAD_URL="https://github.com/elixir-lang/elixir/archive/${ELIXIR_VERSION}.tar.gz" \
	&& ELIXIR_DOWNLOAD_SHA256="07d66cf147acadc21bd1679f486efd6f8d64a73856ecc83c71b5e903081b45d2" \
	&& curl -fSL -o elixir-src.tar.gz $ELIXIR_DOWNLOAD_URL \
	&& echo "$ELIXIR_DOWNLOAD_SHA256  elixir-src.tar.gz" | sha256sum -c - \
	&& mkdir -p /usr/local/src/elixir \
	&& tar -xzC /usr/local/src/elixir --strip-components=1 -f elixir-src.tar.gz \
	&& rm elixir-src.tar.gz \
	&& cd /usr/local/src/elixir \
	&& make install clean \
	&& find /usr/local/src/elixir/ -type f -not -regex "/usr/local/src/elixir/lib/[^\/]*/lib.*" -exec rm -rf {} + \
	&& find /usr/local/src/elixir/ -type d -depth -empty -delete

## Done installing elixir, let's clone the repo

RUN git clone https://github.com/andrlime/Wildhacks2023.git
RUN cd backend
RUN mix deps.get
RUN mix compile
CMD ["mix run --no-halt"]
